# Generated by Django 4.2.5 on 2023-09-24 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_newtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinThis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('userEmail', models.EmailField(max_length=255)),
                ('cityName', models.CharField(max_length=50)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='newTable',
        ),
    ]
